### ISSUE TITLE
Sharp memory spike and crash with RedisGraph

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#148]
Created by: @manoja1
Source: https://github.com/RedisGraph/RedisGraph/issues/1172
Hello, I see a sharp spike in memory from 10 MB to 1 GB when running a query. I could reproduce it with neo4j movie database

MATCH p=(m)-[*0..10]-(n:Person) WHERE n.name='Tom Hanks' RETURN p 

The server became completely unresponsive. I am running the docker image from redislabs.

![Screen Shot 2020-06-28 at 1 46 31 AM](https://user-images.githubusercontent.com/33231759/85942969-c7f38880-b8e1-11ea-90e1-08ba04f0defc.png)

I recognize this is not an efficient query and if the graph has cycles then the engine needs to resolve them. So it's reasonable for the query to timeout but the 100x memory spike is concerning.

**Comment by gkorland** [comment]
Origin comment by: @gkorland
@manoja1 how big is your graph? and how big is the result set?

**Comment by gkorland** [comment]
Origin comment by: @manoja1
For the example  Movie dataset the graph is fairly small  ~ 200 entities and 300 relationships, see attached
<img width="1882" alt="Screen Shot 2020-06-28 at 10 20 13 AM" src="https://user-images.githubusercontent.com/33231759/85954097-f301ca80-b929-11ea-81af-2b276139fb59.png">
So the resultset can't be any bigger than my entire graph.

When I query for Depth 1, it's responsive
<img width="1885" alt="Screen Shot 2020-06-28 at 10 20 23 AM" src="https://user-images.githubusercontent.com/33231759/85954109-07de5e00-b92a-11ea-8bae-0914e2a8916c.png">

If I query for Depth 2, it spins forever, doesn't timeout 
<img width="1897" alt="Screen Shot 2020-06-28 at 10 28 46 AM" src="https://user-images.githubusercontent.com/33231759/85954141-2e9c9480-b92a-11ea-9b03-c9aeb0a6fcfa.png">

If I query for Depth 10 memory spikes to a 784MB as shown in graph above and query times out.
<img width="1899" alt="Screen Shot 2020-06-28 at 10 30 12 AM" src="https://user-images.githubusercontent.com/33231759/85954178-6d324f00-b92a-11ea-9dca-a46e89e6203a.png">

For my real dataset, the total number of nodes was ~ 2-3 K Entities and relationships, and Mem spikes up to over 1 GB in an instant.

**Comment by gkorland** [comment]
Origin comment by: @manoja1
Some update. When I run my query from `redis-cli` I receive response back in many of my queries in reasonable time. And the memory consumption is lower than what I see when I execute them from redisinsights, see graph. It's likely many of the issues are likely rooted in the `redisinsights` Ogma Visualization layer.
<img width="304" alt="Screen Shot 2020-06-29 at 6 41 33 PM" src="https://user-images.githubusercontent.com/33231759/86073274-44987b00-ba38-11ea-8de3-669446f27bdd.png">

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
can you please provide the `MONITOR` output for both scenarios? (cli and redis insight)

**Comment by gkorland** [comment]
Origin comment by: @manoja1
How do I capture the monitor output for redis insight?

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
Run the Redis server that you will connect to with Redis Insight 
Open Redis cli terminal 
Type monitor
Execute the query from Redis Insight

**Comment by gkorland** [comment]
Origin comment by: @K-Jo
@slemeur FYI

**Comment by gkorland** [comment]
Origin comment by: @slemeur
We'll try to reproduce and give a look at this issue: @GnaneshKunal and @nishantgeorge

**Comment by gkorland** [comment]
Origin comment by: @manoja1
Sharing Monitor output for redis-insight

Query `MATCH p=(m)-[*0..10]-(n:Person) WHERE n.name='Tom Hanks' RETURN p ` 
redis monitor 
```
1594953797.714335 [0 172.17.0.1:57948] "INFO" "ALL"
1594953799.867313 [0 172.17.0.1:57872] "INFO"
1594953801.120822 [0 172.17.0.1:57884] "GRAPH.QUERY" "Movie" "MATCH (n) RETURN n LIMIT 1"
1594953801.122765 [0 172.17.0.1:57884] "GRAPH.QUERY" "Movie" "MATCH p=(m)-[*0..10]-(n:Person) WHERE n.name='Tom Hanks' RETURN p" "--compact"
1594953804.914889 [0 172.17.0.1:57872] "INFO"
1594953809.949932 [0 172.17.0.1:57872] "INFO"
1594953812.727778 [0 172.17.0.1:57952] "INFO" "ALL"
```
 Memory spiked to 800 MB then query timed out 

![Screen Shot 2020-07-16 at 7 45 05 PM](https://user-images.githubusercontent.com/33231759/87743122-17b8c780-c79d-11ea-8c8e-89e9326bb2ff.png)

Query : MATCH p=(m)-[*0..2]-(n:Person) WHERE n.name='Tom Hanks' RETURN p
Memory graph remains flat but UI Keeps spinning
Monitor Output 
```
1594954268.465004 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH (n) RETURN n LIMIT 1"
1594954268.477162 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH p=(m)-[*0..2]-(n:Person) WHERE n.name='Tom Hanks' RETURN p" "--compact"
1594954268.526389 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.labels()" "--compact"
1594954268.529686 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.propertyKeys()" "--compact"
1594954268.534366 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.relationshipTypes()" "--compact"
1594954268.544712 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH (n)-[t]->(m) WHERE ID(n) IN [0, 1, 128, 4, 5, 6, 7, 136, 9, 10, 11, 8, 19, 20, 22, 151, 24, 25, 26, 158, 34, 35, 164, 165, 166, 39, 40, 38, 37, 36, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 74, 84, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 105, 116, 117] OR ID(m) IN [0, 1, 128, 4, 5, 6, 7, 136, 9, 10, 11, 8, 19, 20, 22, 151, 24, 25, 26, 158, 34, 35, 164, 165, 166, 39, 40, 38, 37, 36, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 74, 84, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 105, 116, 117] RETURN DISTINCT t" "--compact"
1594954270.437898 [0 172.17.0.1:57872] "INFO"
1594954275.494631 [0 172.17.0.1:57872] "INFO"
1594954277.727752 [0 172.17.0.1:58080] "INFO" "ALL"
```

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@manoja1 
RedisInsight has an overhead, so I want to isolate the problem, can you please execute those queries from CLI and share if there are a timeout and memory spike?

**Comment by gkorland** [comment]
Origin comment by: @GnaneshKunal
Hey @DvirDukhan @manoja1 

I have been looking at the issue and found out that memory spike is an issue with RedisGraph and _not being able to see the graph visualization after the result has arrived_ is a problem with RedisInsight's ogma layer.

RedisInsight doesn't have a big overhead. If you look at the additional queries that are run from RedisInsight,
```
1594954268.465004 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH (n) RETURN n LIMIT 1"
1594954268.477162 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH p=(m)-[*0..2]-(n:Person) WHERE n.name='Tom Hanks' RETURN p" "--compact" (**USER QUERY**)
1594954268.526389 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.labels()" "--compact"
1594954268.529686 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.propertyKeys()" "--compact"
1594954268.534366 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "CALL db.relationshipTypes()" "--compact"
1594954268.544712 [0 172.17.0.1:58076] "GRAPH.QUERY" "Movie" "MATCH (n)-[t]->(m) WHERE ID(n) IN [0, 1,....] OR ID(m) IN [0, ...] RETURN t
```
apart from the final command, nothing is a big overhead and the last one may look like _an overhead_ but that command basically returns quickly without much memory consumption.


Here's a video of the same query but with a different dataset. The dataset contains 1.8K nodes and 1.3K relationships and the query is run on CLI. https://streamja.com/noEjz
Sometimes for the same query, I get 800MB memory consumption but this is the only time I have got 1GB as the consumption. Also, timeouts happens randomly.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@GnaneshKunal can you share the dataset?

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@manoja1 
I built and run `master` on my local machine (Mac, 16GB RAM)
I loaded the imdb demo we have into RedisGraph. The graph has 1602 nodes, 1839 edges.
I executed this query on my machine:
`graph.query imdb "MATCH p= ()-[*0..10]-() RETURN p"`
notice that you requested all the undirected paths in the graph up to the length of 10
For the graph this gives 5858994 paths. and in the general case, this number is not bounded by the graph size, but I believe it is bounded by the size of the graph superset.
The memory output is
```
used_memory:4996032
used_memory_human:4.76M
used_memory_rss:3141632
used_memory_rss_human:3.00M
used_memory_peak:5735996784
used_memory_peak_human:5.34G
used_memory_peak_perc:0.09%
used_memory_overhead:1062012
used_memory_startup:1027968
used_memory_dataset:3934020
used_memory_dataset_perc:99.14%
allocator_allocated:4959104
allocator_active:3103744
allocator_resident:3103744
total_system_memory:17179869184
total_system_memory_human:16.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:0.63
allocator_frag_bytes:18446744073707696256
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.01
rss_overhead_bytes:37888
mem_fragmentation_ratio:0.63
mem_fragmentation_bytes:-1817472
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:33972
mem_aof_buffer:0
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0
```
total execution time:
`Query internal execution time: 538428.555000 milliseconds`

**Comment by gkorland** [comment]
Origin comment by: @GnaneshKunal
> @GnaneshKunal can you share the dataset?
> 

@DvirDukhan The same IMDB dataset.

**Comment by gkorland** [comment]
Origin comment by: @slemeur
@DvirDukhan : When you run performance/memory stress tests - how are you doing this? We would like to see how we could benefit from this experience with redisinsight tests.

**Comment by gkorland** [comment]
Origin comment by: @GnaneshKunal
@DvirDukhan @manoja1 

I have found another reason for the memory spike and the reason why there's a time difference between redis-cli and redisinsight for the query.

We are using [redisgraph-py](https://github.com/RedisGraph/redisgraph-py) in redisinsight. By default, the queries that are submitted to redisinsight are run with a `--compact` flag (you can check the same by running `MONITOR`).

Without compact flag, only IDs of the [named paths](https://oss.redislabs.com/redisgraph/commands/#named-paths) are being returned but with compact flag, metadata and properties of the entities are also returned. 

Here's a demonstration:
https://streamja.com/LMoXv

It's also strange that the query with `--compact` flag doesn't run on redis-cli (or random python program) but runs in redisinsight.

```
# redis-cli
127.0.0.1:6379> GRAPH.QUERY rg:social "MATCH p=(m)-[*0..5]-(n) RETURN p" --compact
Error: No support for nested multi bulk replies with depth > 7
```

```
gnanesh_r@LAP-LIN-642:/tmp$ python3                                                                                           
Python 3.6.7 (default, Mar 10 2020, 12:19:25) 
[GCC 9.2.1 20200304] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from redisgraph import Graph
>>> from redis import Redis
>>> r = Redis()
>>> rg = Graph('rg:social', r)
>>> rg.query('MATCH p=(m)-[*0..5]-(n) RETURN p')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gnanesh_r/.pyenv/versions/3.6.7/lib/python3.6/site-packages/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/home/gnanesh_r/.pyenv/versions/3.6.7/lib/python3.6/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/gnanesh_r/.pyenv/versions/3.6.7/lib/python3.6/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/home/gnanesh_r/.pyenv/versions/3.6.7/lib/python3.6/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/home/gnanesh_r/.pyenv/versions/3.6.7/lib/python3.6/site-packages/redis/connection.py", line 464, in read_response
    response = self._reader.gets()
redis.exceptions.InvalidResponse: No support for nested multi bulk replies with depth > 7

```

**Comment by gkorland** [comment]
**Triage note:** This issue reports a 100x memory spike (10MB → 1GB) with variable-length unbounded paths:
```
MATCH p=(m)-[*0..10]-(n:Person) WHERE n.name='Tom Hanks' RETURN p
```
Unbounded variable-length paths with cycles can cause exponential expansion, but a 100x memory spike may indicate the engine isn't bounding intermediate results effectively. Is this still reproducible on the current version?
