### ISSUE TITLE
RedisGraph crashes with Failed Assertion

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/FalkorDB#171]
Created by: @arramos84
Source: https://github.com/RedisGraph/RedisGraph/issues/1373
Our redisgraph seems to have crashed from a query. CPU spiked up right before it happened. We are running `redislabs/redigraph:latest`. Not sure what the query that triggered this was, will turn on slowlog to capture this for future issues if possible.

Attached is the crash report. Thanks!

[redis-crash.txt](https://github.com/RedisGraph/RedisGraph/files/5350356/redis-crash.txt)

@DvirDukhan

**Comment by gkorland** [comment]
Origin comment by: @manoja1
Pod CPU Limit set to 0.8, CPU Spiked, and then Pod Crashed with Log
<img width="2889" alt="Screen Shot 2020-10-08 at 10 32 45 AM" src="https://user-images.githubusercontent.com/33231759/95493766-c6f6dc00-0951-11eb-9567-ea858346ea15.png">

Pod Memory Usage(MB)
<img width="2897" alt="Screen Shot 2020-10-08 at 10 33 00 AM" src="https://user-images.githubusercontent.com/33231759/95493851-e988f500-0951-11eb-9603-1c8b35263383.png">
 is trivial < 10MB and No spike in Memory right around the time Pod Crashed

**Comment by gkorland** [comment]
Origin comment by: @gkorland
Can you please try it with 2.2.6? 
`redislabs/redigraph:2.2.6`

**Comment by gkorland** [comment]
Origin comment by: @arramos84
Will try to by switching to `2.2.6` and seeing if the issue comes back again.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84 Thanks for reporting
I'm waiting for your input on 2.2.6 or reproduce steps.
Thanks

**Comment by gkorland** [comment]
Origin comment by: @manoja1
The crash re-occurred with v 2.2.6. We will try to isolate the query we were running around that time.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@manoja1 can you provide 2.2.6 crash logs?

**Comment by gkorland** [comment]
Origin comment by: @arramos84
> @manoja1 can you provide 2.2.6 crash logs?

@DvirDukhan , here are the logs.
[redis-crash-20201013.txt](https://github.com/RedisGraph/RedisGraph/files/5374664/redis-crash-20201013.txt)

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84 
Any updates on the queries that crash it?

**Comment by gkorland** [comment]
Origin comment by: @arramos84
@DvirDukhan, looks like what caused the crash was an undirected query like this:

`match (n:Namespace)-[*0..10]-()-[r:CAUSING]->(a:Assertion) where n.name = 'petclinic' return count(distinct r)`

We notice that sometimes there is a crash, and sometimes there is a high CPU spike/throttle that brings the redis instance to its knees for an extended period of time (10's of minutes). 

I think we need to do some additional testing to definitively determine what is going on. We were looking at a data corruption issue as priority most recently.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84 
1. We will check the query, thanks.
2. Regarding the second issue, just use RDB persistency for now. When your server will recover the schema will be persistent with the crashed instance schema.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84 
can you provide graph construction queries, that after executing them will cause the crash?
Doing a naive test is not so helpful as the crash is not reproducing.
```
127.0.0.1:6379> graph.query g "CREATE (:Namespace {name: 'petclinic'})-[:CAUSING]->(:Namespace {name: 'petclinit'})-[:CAUSING]->(:Assertion)"
1) 1) "Labels added: 2"
   2) "Nodes created: 3"
   3) "Properties set: 2"
   4) "Relationships created: 2"
   5) "Cached execution: 0"
   6) "Query internal execution time: 1.108900 milliseconds"
127.0.0.1:6379> graph.query g "match (n:Namespace)-[*0..10]-()-[r:CAUSING]->(a:Assertion) where n.name = 'petclinic' return count(distinct r)"
1) 1) "count(distinct r)"
2) 1) 1) (integer) 1
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 3.382000 milliseconds"
```

**Comment by gkorland** [comment]
Origin comment by: @manoja1
@DvirDukhan can we provide an exported dump of our graph db, it's less than <10MB in memory. please advise on how we can provide the export.

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84

You can email us a dump by running
`SAVE` or `BGSAVE`
on cli
and send `dump.rdb`

**Comment by gkorland** [comment]
Origin comment by: @arramos84
@DvirDukhan , you should have received it in your email. Thanks!

**Comment by gkorland** [comment]
Origin comment by: @DvirDukhan
@arramos84 
Can you verify that this is indeed the query that caused a crash?
I cannot reproduce the crash since the query takes an extremely long time to run, while the server is still responding properly (e.g. no deadlock).
You are using an undirected path with a length of 10. I tried to understand why the query does not stop after a few hours so I tried to check the number of possible results that you can get. I stopped at a path with a length of 5, as you can see, the number of results and the runtime will just increase:
```
127.0.0.1:6379> graph.query dev "MATCH p=(:Namespace)-[*0..1]-() return count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 176
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 1.912000 milliseconds"
127.0.0.1:6379> graph.query dev "MATCH p=(:Namespace)-[*0..2]-() return count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 1807
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 7.585000 milliseconds"
127.0.0.1:6379> graph.query dev "MATCH p=(:Namespace)-[*0..3]-() return count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 32024
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 103.605000 milliseconds"
127.0.0.1:6379> graph.query dev "MATCH p=(:Namespace)-[*0..4]-() return count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 1367964
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 4203.384000 milliseconds"
(4.21s)
127.0.0.1:6379> graph.query dev "MATCH p=(:Namespace)-[*0..5]-() return count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 74211395
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 241694.758000 milliseconds"
(241.69s)
```
I think it is related to #1172, which we have discussed in a previous call.
So, in order to proceed, please validate that this is in fact the problematic query. If so, how much time does it takes to crash?

**Comment by gkorland** [comment]
Origin comment by: @manoja1
@DvirDukhan We are sending you a new dump. We just fired the query from redis CLI and the pod goes on a CPU Spin and all other client services are getting time out exception
```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:155) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.Connection.getOne(Connection.java:296) ~[jedis-3.1.0.jar!/:na]
	at redis.clients.jedis.Jedis.sendCommand(Jedis.java:3835) ~[jedis-3.1.0.jar!/:na]
	at com.redislabs.redisgraph.impl.api.ContextedRedisGraph.sendQuery(ContextedRedisGraph.java:52) ~[jredisgraph-2.1.0.jar!/:na]
	at com.redislabs.redisgraph.impl.api.RedisGraph.sendQuery(RedisGraph.java:68) ~[jredisgraph-2.1.0.jar!/:na]
	at com.redislabs.redisgraph.impl.api.AbstractRedisGraph.query(AbstractRedisGraph.java:65) ~[jredisgraph-2.1.0.jar!/:na]
	at ai.asserts.model.redis.RedisKGraph.upsertEntity(RedisKGraph.java:116) ~[model-graph-redis-20.10.0.bf7ad4f.jar!/:na]
```

We can't send any query from CLI or UI or from our service

Here are the charts for resource usage

CPU
<img width="2725" alt="Screen Shot 2020-10-26 at 12 31 42 PM" src="https://user-images.githubusercontent.com/33231759/97219974-06159180-1788-11eb-84ce-7a5a6129b007.png">


Memory

<img width="2756" alt="Screen Shot 2020-10-26 at 12 36 23 PM" src="https://user-images.githubusercontent.com/33231759/97220010-1299ea00-1788-11eb-972e-eea423cded94.png">


Disk

 
<img width="2747" alt="Screen Shot 2020-10-26 at 12 36 02 PM" src="https://user-images.githubusercontent.com/33231759/97220029-19c0f800-1788-11eb-8981-38589023ab50.png">

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Performing a variable length traversal with depth of 10 on bidirectional edges `()-[*0..10]-()`
can generate an enormous number of paths, as @DvirDukhan has shared above
```
MATCH p=(:Namespace)-[*0..5]-() return count(p)
```
Performing a variable length traversal of length 5 on a direction agnostic edge in your graph will yield 74,211,395 different paths.

Computing all of these paths will take time, cpu will spike and memory will increase.
The question is do you really need all of these results?
My guess performing a 10 hops variable traversal as you do, will yield over a quadrillionth (10^15) different paths.

**Comment by gkorland** [comment]
Origin comment by: @manoja1
We won't be running these queries in Production. As we mentioned in the original ticket, we have found the graph DB crashing or going on a CPU Spin with certain queries. We have not been able to isolate what specific queries that cause it to crash, we only have the crash log. 

With that said if someone accidentally fires a fatal quey, that takes forever to execute, the only recovery path is to force kill the graph instance and restart it. Will it be possible to implement a circuit breaker that terminates the execution based on a set threshold?

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Yes, it is possible to specify a timeout on a query, see [doc](https://oss.redislabs.com/redisgraph/configuration/#query-timeout)

**Comment by gkorland** [comment]
Origin comment by: @manoja1
I ran a few simple tests to verify if the timeout is truly timing out the execution in the graph server by running the following in a CLI  and observing the CPU usage

```
redis-cli -p 6739 graph.query dev "match (n:Namespace)-[*0..10]-()-[r:CAUSING]->(a:Assertion) where n.name = 'petclinic' return count(distinct r)" timeout 1000
```

After triggering the above manually 10 - 20 times I observed while the query is timing out the CPU was steadily rising. I also noticed the graph had crashed once and restarted between these runs

So I decided to run the query in a loop. Please note there is only a single instance of the query running at a time from the CLI
```
while true; do  redis-cli -p 6739 graph.query dev "match (n:Namespace)-[*0..10]-()-[r:CAUSING]->(a:Assertion) where n.name = 'petclinic' return count(distinct r)" timeout 10 ; done
```  

I observed the CPU spiked up to max_provisioned very soon. 

see pod cpu graph, the first peak is `manual` run, 2nd peak is `loop` run
<img width="2686" alt="Screen Shot 2020-10-27 at 6 25 15 PM" src="https://user-images.githubusercontent.com/33231759/97379434-0a25da00-1882-11eb-90ae-50895bc09f8a.png">

When I terminated the `loop` run with `Ctrl+C` a couple of times I noticed the graph instance was crashing. see the gaps in  `redis_user_cpu` captured from redis exporter.
<img width="1795" alt="Screen Shot 2020-10-27 at 6 26 21 PM" src="https://user-images.githubusercontent.com/33231759/97379587-5a9d3780-1882-11eb-8aba-174d321d2ead.png">

and the redis_uptime counter reset for the same period
<img width="1711" alt="Screen Shot 2020-10-27 at 6 30 11 PM" src="https://user-images.githubusercontent.com/33231759/97379665-87514f00-1882-11eb-8dc8-95de9f94b52d.png">

I then suspected if the abrupt termination of timeout queries has anything to do with the crashes. So I ran a much simpler query that only takes 0.1 ms with a timeout setting
```
while true; do  redis-cli -p 6739 graph.query dev "match (n) return count(n)" timeout 1000 ; done

Handling connection for 6739
1) 1) "count(n)"
2) 1) 1) (integer) 1444
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.112504 milliseconds"
.....

```

I would execute and then terminate with `Ctrl+C`  and then execute again and repeat in quick succession. This caused the graph to crash repeatedly. 

I am attaching 7 crash reports notice the timestamps, the last 3. They are < 2mins apart when I was running the last test.

I then ran the same test without the `timeout` i.e. execute and terminate and execute again and there were no crashes
```
while true; do  redis-cli -p 6739 graph.query dev "match (n) return count(n)" ; done

Handling connection for 6739
1) 1) "count(n)"
2) 1) 1) (integer) 1444
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.112504 milliseconds"
.....
``` 
Summary of my findings.
- With timeout set for a long-running query the CPU continues to spike and takes a while to quiesce down
- The timeout setting is also causing the redisgraph to crash irrespective of the query execution time.

[redis-crash-logs.zip](https://github.com/RedisGraph/RedisGraph/files/5449015/redis-crash-logs.zip)

**Comment by gkorland** [comment]
Origin comment by: @swilly22
@manoja1 killing a client "mid-way" is known to cause a crash, @jeffreylovitz issued a [PR](https://github.com/RedisGraph/RedisGraph/pull/1298/) that address this problem awhile ago and I've just merged it.

With regard to the increase in CPU consumption on the tested timeout query, I'll have to look into it.

**Comment by gkorland** [comment]
Origin comment by: @manoja1
@swilly22 as I mentioned, I could reproduce the crash from CLI every time when the query had a `timeout` clause and could never make it crash when there was `no timeout`. You have the dataset and test case so please verify if the fix is working.

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Hi @manoja1,
I've tried reproducing the crash described but wasn't able to, I've tried using different queries and different timeouts
In case you do manage to trigger a crash on our latest version (2.2.8) please provide the crash log.

**Comment by gkorland** [comment]
Origin comment by: @manoja1
Hi @swilly22, I have verified the fix, it's not crashing anymore. 

Regarding the spike in CPU consumption  

Here is a chart for the cpu Usage when I ran the following from CLI
`while true; do  redis-cli -p 6739 graph.query dev "match (n:Namespace)-[*0..10]-()-[r:CAUSING]->(a:Assertion) where n.name = 'petclinic' return count(distinct r)" timeout 10 ; done`

The spike is just about 3x with v2.2.8, it's not reaching the max cpu provisioned
 
<img width="1919" alt="Screen Shot 2020-11-16 at 8 31 20 PM" src="https://user-images.githubusercontent.com/33231759/99347064-f5b67b00-284a-11eb-84c3-1b147f52bc49.png">

Please confirm this is the expected behavior.

**Comment by gkorland** [comment]
Origin comment by: @swilly22
Glad to hear there's no crash,
With regard to the CPU usage I would assume it would vary depending on the underline architecture, as such I can't confirm this behavior, I would need to free up some time to really dig deep into this.
